name: Run it on action

on:
  push:
    branches:
      - master
  schedule:
    - cron: 15 10,22 * * *
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Run it on action
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: PHP
        uses: franzliedke/gh-action-php@master
      - name: Run
        run: |
          if [ '${{ secrets.BDUSS }}' != '' ]; then sed -i "s/xxxxx/${{ secrets.BDUSS }}/" tieba.php; fi
          php tieba.php